#These constants can be modified to generate different family sizes
MIN_GENERATIONS = 5
MAX_GENERATIONS = 5

MIN_CHILDREN = 1
MAX_CHILDREN = 1

MIN_AGE_YEARS = 0
MAX_AGE_YEARS = 120

PARENTING_MIN_AGE = 15
PARENTING_MAX_AGE = 60

FAMILY_MIN_POPULATION = 1
FAMILY_MAX_POPULATION = 1

GENERATIONS_PACE_YEARS = 30